Umbrella.Blog.Web/Umbrella.Blog.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Security;
using Umbrella.Blog.BLL;
using Umbrella.Blog.Models;
using Umbrella.Blog.Web.Models;

namespace Umbrella.Blog.Web.Controllers
{
    public class CategoryController : Controller
    {

        CategoryManager categoryManager = new CategoryManager();
        [System.Web.Mvc.Authorize(Roles = "Admin,Employee")]
        public ActionResult Manage()
        {
            CategoryVM viewModel = new CategoryVM();
            IEnumerable<Category> s = categoryManager.GetAllCategories().Data; ;
            
            ViewBag.Message = "Category Edit Page";

            return View(s);
        }
        [System.Web.Mvc.Authorize(Roles = "Admin,Employee")]
        [System.Web.Mvc.AcceptVerbs("POST")]
        public ActionResult Edit(Category catmodel)
        {
            CategoryVM viewModel = new CategoryVM();
            IEnumerable<Category> s = categoryManager.GetAllCategories().Data; ;


            return View(s);
        }
    }
}

Umbrella.Blog.Web/Umbrella.Blog.Web/Controllers/TinyMCESampleController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Umbrella.Blog.BLL;
using Umbrella.Blog.Models;
using Umbrella.Blog.Web.Models;

namespace Umbrella.Blog.Web.Controllers {

    public class TinyMCESampleController : Controller {

        //
        // GET: /TinyMCESample/
        PostManager postManager = new PostManager();
        CategoryManager categoryManager = new CategoryManager();

        [HttpGet]
        public ActionResult TinyMCECreatePost() {

            TinyMCEModel tinyMCEModel = new TinyMCEModel();
            tinyMCEModel.SetCategoryDropDownItems(categoryManager.GetAllCategories().Data);

            return View(tinyMCEModel);

        }

        [Authorize(Roles = "Admin,Employee")]
        [HttpPost]
        public ActionResult TinyMCECreatePost(TinyMCEModel model)
        {

            if (!model.HtmlContent.Contains("<p>") && !model.HtmlContent.Contains("</p>") && !model.HtmlContent.Contains("<p") && !model.HtmlContent.Contains("<img"))
            {
                ModelState.AddModelError("HtmlContent",
                    "Please enter text for your post!");
            }
            Post post = new Post();
            if (ModelState.IsValid)
            {
            TagManager tagManager = new TagManager();
           
            post.PostTitle = model.Title;
            post.PostText = model.HtmlContent;
            post.PostDate = DateTime.Now;
            post.UserId = "00000000-0000-0000-0000-000000000000";
            post.ExpirationDate = model.ExpirationDate;
            post.CategoryId = model.CategoryId;
            post = postManager.CreatePost(post);

            if (!string.IsNullOrWhiteSpace(model.TagString))
            {
                string[] tagInputFromView = model.TagString.Trim().Split(',');
                Tag tag = new Tag();
                foreach (var t in tagInputFromView)
                {
                    tag.TagText = t.Trim();
                    tag = tagManager.CreateTag(tag);
                    tagManager.CreatePostTagLink(tag.TagId, post.PostId);
                }
            }
            return RedirectToAction("Edit", new { postId = post.PostId });
            }
            else
            {
                model.SetCategoryDropDownItems(categoryManager.GetAllCategories().Data);
                return View(model);  
            }
            
        }

        [Authorize(Roles = "Admin,Employee")]
        [HttpGet]        
        public ActionResult Edit(int postId)
        {
            var post = postManager.GetPostById(postId).Data;
            
            TinyMCEModel editVM = new TinyMCEModel()
            {
                Id = post.PostId,
                Title = post.PostTitle,
                CategoryId = post.CategoryId,
                HtmlContent = post.PostText,
                Approved = post.Approved,
                ExpirationDate = post.ExpirationDate ?? DateTime.MaxValue
            };


            if (post.Tags.Count != 0)
            {
                foreach (var t in post.Tags)
                {
                    editVM.Tags.Add(t);
                }
            }

            
            editVM.SetCategoryDropDownItems(categoryManager.GetAllCategories().Data);

            return View(editVM);
        }

        [Authorize(Roles = "Admin,Employee")]
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Edit(TinyMCEModel model)
        {

            if (!model.HtmlContent.Contains("<p>") || !model.HtmlContent.Contains("</p>"))
            {
                ModelState.AddModelError("HtmlContent",
                    "Please enter text for your post!");
            }
            TagManager tagManager = new TagManager();
            PostManager postManager = new PostManager();
            Post post = new Post();

            if (ModelState.IsValid)
            {

                post.PostId = model.Id;
                post.PostTitle = model.Title;
                post.PostText = model.HtmlContent;
                post.Approved = model.Approved;
                post.PostDate = DateTime.Now;
                post.UserId = "00000000-0000-0000-0000-000000000000";
                post.CategoryId = model.CategoryId;
                post.ExpirationDate = model.ExpirationDate;
                post = postManager.Edit(post).Data;

                if (!string.IsNullOrWhiteSpace(model.TagString))
                {
                    string[] tagInputFromView = model.TagString.Trim().Split(',');
                    Tag tag = new Tag();
                    foreach (var t in tagInputFromView)
                    {
                        tag.TagText = t.Trim();
                        tag = tagManager.CreateTag(tag);
                        tagManager.CreatePostTagLink(tag.TagId, model.Id);
                    }
                }
                return RedirectToAction("BlogPost", "Home", new { model.Id } );
            }
            post = postManager.GetPostById(model.Id).Data;
            model.Tags = post.Tags;
            model.SetCategoryDropDownItems(categoryManager.GetAllCategories().Data);
            return View(model);
            //else
            //{
            //    return View("Edit", new { postId = model.Id });
            //}
        }


        [Authorize(Roles = "Admin,Employee")]
        [ValidateInput(false)]
        [HttpGet]
        public ActionResult DeleteTag(int postId, int tagId)
        {
            postManager.RemoveTags(tagId, postId);

            return RedirectToAction("Edit", new { postId = postId });
        }
    }
    
}

Umbrella.Blog.Web/Umbrella.Blog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.10.2.js"></script>
  
    <script>

        $(document)
            .ready(function () {
                getData();
            });

        
        function getData() {
            var settings = {
                "async": true,
                "crossDomain": true,
                "url": "http://localhost:59924/api/menuitems",
                "method": "GET",
                "headers": {
                    "content-type": "application/x-www-form-urlencoded",
                    "cache-control": "no-cache",
                    "postman-token": "5c761847-ff03-400f-fdeb-c6f4eb3b701d"
                }
            }
            $.ajax(settings)
                .done(function (response) {
                    renderMenu(response);
                });
        }

        function renderMenu(data) {
            var documentObject = document.getElementById("custom_pages");
            var htmlToAdd = '';
            console.log(data[0])
            for (var i = 0; i < data.length; i++) {
                htmlToAdd += '<li> <a href="' + data[i].MenuLink + '">' + data[i].MenuText + '</a></li>';
            }
            documentObject.insertAdjacentHTML('beforeend', htmlToAdd);
        }



    </script>

</head>
<body >
    <div class="Logo-Header" id="LogoHeader" @*data-spy="affix"*@ >
        <img id="HeadLogo" style="width:25%; position:relative" src="~/Images/10.png" alt="Company-Logo" />
    </div >
        <div class="navbar navbar-inverse" >
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span  class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("The Umbrella Corporation", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Blog", "Blog", "Home")</li>

                        @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
                                <ul class="dropdown-menu">
@if (User.IsInRole("Admin"))
{
                                    <li>@Html.ActionLink("Categories", "Manage", "Category")</li>
    <li>@Html.ActionLink("Users", "ListUser", "Account")</li>

}
                                   
                                    <li>@Html.ActionLink("Create Post", "TinyMCECreatePost", "TinyMCESample")</li>
                                    
                                    <li>@Html.ActionLink("Manage Menu", "ManageMenu", "Manage")</li>

                                </ul>
                            </li>
                            
                        }
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pages<span class="caret"></span></a>
                            <ul id="custom_pages" class="dropdown-menu">


                            </ul>
                        </li>

                    </ul>

                    @Html.Partial("_LoginPartial")
                </div>

            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            
            
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>